#! /usr/bin/env bash

source /home/chris/local/miniconda3/bin/activate thesis

echo "Database export"
python data_unifier.py nordkette
python data_unifier.py cosmo7
python data_unifier.py raso
python data_unifier.py tb_igmk
python data_unifier.py cloudy_igmk

echo "Brightness temperatures"
python data_unifier.py --levels 180 tb_monortm > /dev/null &
python data_unifier.py --levels 4000 tb_mwrtm_full &
python data_unifier.py --levels 2500 --source "../data/unified/<VAR>_raso.csv" tb_mwrtm_fap &
python data_unifier.py --levels 5000 --source "../data/unified/<VAR>_raso.csv" tb_mwrtm_fap &
wait

echo "done!"
