#! /usr/bin/env bash

source /home/chris/local/miniconda3/bin/activate thesis

python db_import.py create_tables ../data/amalg.db

python db_import.py raso_fwf ../data/amalg.db --pid=1

python db_import.py raso_cosmo7 ../data/amalg.db --pid=1

python db_import.py raso_bufr ../data/db_parts/raso_bufr01.db --pid=3200 --offset=0   --size=80 &
python db_import.py raso_bufr ../data/db_parts/raso_bufr02.db --pid=3280 --offset=80  --size=80 &
python db_import.py raso_bufr ../data/db_parts/raso_bufr03.db --pid=3360 --offset=160 --size=80 &
python db_import.py raso_bufr ../data/db_parts/raso_bufr04.db --pid=3440 --offset=240 --size=80 &
python db_import.py raso_bufr ../data/db_parts/raso_bufr05.db --pid=3520 --offset=320 --size=80 &
python db_import.py raso_bufr ../data/db_parts/raso_bufr06.db --pid=3600 --offset=400 --size=100 &
python db_import.py raso_bufr ../data/db_parts/raso_bufr07.db --pid=3700 --offset=500 --size=100 &
python db_import.py raso_bufr ../data/db_parts/raso_bufr08.db --pid=3800 --offset=600 --size=100 &
python db_import.py raso_bufr ../data/db_parts/raso_bufr09.db --pid=4900 --offset=700 --size=100 &
python db_import.py raso_bufr ../data/db_parts/raso_bufr10.db --pid=4000 --offset=800 &

wait

sqlite3 ../data/amalg.db <<< '''
ATTACH "../data/db_parts/raso_bufr01.db" AS bufr01;
ATTACH "../data/db_parts/raso_bufr02.db" AS bufr02;
ATTACH "../data/db_parts/raso_bufr03.db" AS bufr03;
ATTACH "../data/db_parts/raso_bufr04.db" AS bufr04;
ATTACH "../data/db_parts/raso_bufr05.db" AS bufr05;
ATTACH "../data/db_parts/raso_bufr06.db" AS bufr06;
ATTACH "../data/db_parts/raso_bufr07.db" AS bufr07;
ATTACH "../data/db_parts/raso_bufr08.db" AS bufr08;
ATTACH "../data/db_parts/raso_bufr09.db" AS bufr09;
ATTACH "../data/db_parts/raso_bufr10.db" AS bufr10;

INSERT INTO raso SELECT * FROM bufr01.raso;
INSERT INTO raso SELECT * FROM bufr02.raso;
INSERT INTO raso SELECT * FROM bufr03.raso;
INSERT INTO raso SELECT * FROM bufr04.raso;
INSERT INTO raso SELECT * FROM bufr05.raso;
INSERT INTO raso SELECT * FROM bufr06.raso;
INSERT INTO raso SELECT * FROM bufr07.raso;
INSERT INTO raso SELECT * FROM bufr08.raso;
INSERT INTO raso SELECT * FROM bufr09.raso;
INSERT INTO raso SELECT * FROM bufr10.raso;

INSERT INTO rasodata (parent, p, z, T, Td) SELECT parent, p, z, T, Td FROM bufr01.rasodata ORDER BY id ASC;
INSERT INTO rasodata (parent, p, z, T, Td) SELECT parent, p, z, T, Td FROM bufr02.rasodata ORDER BY id ASC;
INSERT INTO rasodata (parent, p, z, T, Td) SELECT parent, p, z, T, Td FROM bufr03.rasodata ORDER BY id ASC;
INSERT INTO rasodata (parent, p, z, T, Td) SELECT parent, p, z, T, Td FROM bufr04.rasodata ORDER BY id ASC;
INSERT INTO rasodata (parent, p, z, T, Td) SELECT parent, p, z, T, Td FROM bufr05.rasodata ORDER BY id ASC;
INSERT INTO rasodata (parent, p, z, T, Td) SELECT parent, p, z, T, Td FROM bufr06.rasodata ORDER BY id ASC;
INSERT INTO rasodata (parent, p, z, T, Td) SELECT parent, p, z, T, Td FROM bufr07.rasodata ORDER BY id ASC;
INSERT INTO rasodata (parent, p, z, T, Td) SELECT parent, p, z, T, Td FROM bufr08.rasodata ORDER BY id ASC;
INSERT INTO rasodata (parent, p, z, T, Td) SELECT parent, p, z, T, Td FROM bufr09.rasodata ORDER BY id ASC;
INSERT INTO rasodata (parent, p, z, T, Td) SELECT parent, p, z, T, Td FROM bufr10.rasodata ORDER BY id ASC;
'''
