#! /usr/bin/env bash

source /home/chris/local/miniconda3/bin/activate thesis

python db_import.py description ../data/amalg.db --create

python db_import.py nordkette ../data/amalg.db
python db_import.py igmk ../data/amalg.db
python db_import.py hatpro ../data/amalg.db
python db_import.py raso_cosmo7 ../data/amalg.db --pid=1
python db_import.py raso_fwf ../data/amalg.db --pid=6000

python db_import.py raso_bufr ../data/db_parts/raso_bufr01.db --create --pid=10000 --offset=0   --size=80 &
python db_import.py raso_bufr ../data/db_parts/raso_bufr02.db --create --pid=10080 --offset=80  --size=80 &
python db_import.py raso_bufr ../data/db_parts/raso_bufr03.db --create --pid=10160 --offset=160 --size=80 &
python db_import.py raso_bufr ../data/db_parts/raso_bufr04.db --create --pid=10240 --offset=240 --size=80 &
python db_import.py raso_bufr ../data/db_parts/raso_bufr05.db --create --pid=10320 --offset=320 --size=80 &
python db_import.py raso_bufr ../data/db_parts/raso_bufr06.db --create --pid=10400 --offset=400 --size=100 &
python db_import.py raso_bufr ../data/db_parts/raso_bufr07.db --create --pid=10500 --offset=500 --size=100 &
python db_import.py raso_bufr ../data/db_parts/raso_bufr08.db --create --pid=10600 --offset=600 --size=100 &
python db_import.py raso_bufr ../data/db_parts/raso_bufr09.db --create --pid=10700 --offset=700 --size=100 &
python db_import.py raso_bufr ../data/db_parts/raso_bufr10.db --create --pid=10800 --offset=800 &

wait

sqlite3 ../data/amalg.db <<< '''
ATTACH "../data/db_parts/raso_bufr01.db" AS bufr01;
ATTACH "../data/db_parts/raso_bufr02.db" AS bufr02;
ATTACH "../data/db_parts/raso_bufr03.db" AS bufr03;
ATTACH "../data/db_parts/raso_bufr04.db" AS bufr04;
ATTACH "../data/db_parts/raso_bufr05.db" AS bufr05;
ATTACH "../data/db_parts/raso_bufr06.db" AS bufr06;
ATTACH "../data/db_parts/raso_bufr07.db" AS bufr07;
ATTACH "../data/db_parts/raso_bufr08.db" AS bufr08;
ATTACH "../data/db_parts/raso_bufr09.db" AS bufr09;
ATTACH "../data/db_parts/raso_bufr10.db" AS bufr10;
INSERT INTO profiles SELECT * FROM bufr01.profiles;
INSERT INTO profiles SELECT * FROM bufr02.profiles;
INSERT INTO profiles SELECT * FROM bufr03.profiles;
INSERT INTO profiles SELECT * FROM bufr04.profiles;
INSERT INTO profiles SELECT * FROM bufr05.profiles;
INSERT INTO profiles SELECT * FROM bufr06.profiles;
INSERT INTO profiles SELECT * FROM bufr07.profiles;
INSERT INTO profiles SELECT * FROM bufr08.profiles;
INSERT INTO profiles SELECT * FROM bufr09.profiles;
INSERT INTO profiles SELECT * FROM bufr10.profiles;
INSERT INTO profiledata (profile, p, z, T, Td, qvap, qliq) SELECT profile, p, z, T, Td, qvap, qliq FROM bufr01.profiledata ORDER BY id ASC;
INSERT INTO profiledata (profile, p, z, T, Td, qvap, qliq) SELECT profile, p, z, T, Td, qvap, qliq FROM bufr02.profiledata ORDER BY id ASC;
INSERT INTO profiledata (profile, p, z, T, Td, qvap, qliq) SELECT profile, p, z, T, Td, qvap, qliq FROM bufr03.profiledata ORDER BY id ASC;
INSERT INTO profiledata (profile, p, z, T, Td, qvap, qliq) SELECT profile, p, z, T, Td, qvap, qliq FROM bufr04.profiledata ORDER BY id ASC;
INSERT INTO profiledata (profile, p, z, T, Td, qvap, qliq) SELECT profile, p, z, T, Td, qvap, qliq FROM bufr05.profiledata ORDER BY id ASC;
INSERT INTO profiledata (profile, p, z, T, Td, qvap, qliq) SELECT profile, p, z, T, Td, qvap, qliq FROM bufr06.profiledata ORDER BY id ASC;
INSERT INTO profiledata (profile, p, z, T, Td, qvap, qliq) SELECT profile, p, z, T, Td, qvap, qliq FROM bufr07.profiledata ORDER BY id ASC;
INSERT INTO profiledata (profile, p, z, T, Td, qvap, qliq) SELECT profile, p, z, T, Td, qvap, qliq FROM bufr08.profiledata ORDER BY id ASC;
INSERT INTO profiledata (profile, p, z, T, Td, qvap, qliq) SELECT profile, p, z, T, Td, qvap, qliq FROM bufr09.profiledata ORDER BY id ASC;
INSERT INTO profiledata (profile, p, z, T, Td, qvap, qliq) SELECT profile, p, z, T, Td, qvap, qliq FROM bufr10.profiledata ORDER BY id ASC;
'''

python db_import.py mwrt ../data/db_parts/mwrt_01.db --create --pid=2750000 --offset=0    --size=500 &
python db_import.py mwrt ../data/db_parts/mwrt_02.db --create --pid=2760000 --offset=500  --size=500 &
python db_import.py mwrt ../data/db_parts/mwrt_03.db --create --pid=2770000 --offset=1000 --size=500 &
python db_import.py mwrt ../data/db_parts/mwrt_04.db --create --pid=2780000 --offset=1500 --size=500 &
python db_import.py mwrt ../data/db_parts/mwrt_05.db --create --pid=2790000 --offset=2000 --size=500 &
python db_import.py mwrt ../data/db_parts/mwrt_06.db --create --pid=2800000 --offset=2500 --size=500 &
python db_import.py mwrt ../data/db_parts/mwrt_07.db --create --pid=2810000 --offset=3000 --size=500 &
python db_import.py mwrt ../data/db_parts/mwrt_08.db --create --pid=2820000 --offset=3500 &

wait

sqlite3 ../data/amalg.db <<< '''
ATTACH "../data/db_parts/mwrt_01.db" AS mwrt01;
ATTACH "../data/db_parts/mwrt_02.db" AS mwrt02;
ATTACH "../data/db_parts/mwrt_03.db" AS mwrt03;
ATTACH "../data/db_parts/mwrt_04.db" AS mwrt04;
ATTACH "../data/db_parts/mwrt_05.db" AS mwrt05;
ATTACH "../data/db_parts/mwrt_06.db" AS mwrt06;
ATTACH "../data/db_parts/mwrt_07.db" AS mwrt07;
ATTACH "../data/db_parts/mwrt_08.db" AS mwrt08;
INSERT INTO hatpro SELECT * FROM mwrt01.hatpro;
INSERT INTO hatpro SELECT * FROM mwrt02.hatpro;
INSERT INTO hatpro SELECT * FROM mwrt03.hatpro;
INSERT INTO hatpro SELECT * FROM mwrt04.hatpro;
INSERT INTO hatpro SELECT * FROM mwrt05.hatpro;
INSERT INTO hatpro SELECT * FROM mwrt06.hatpro;
INSERT INTO hatpro SELECT * FROM mwrt07.hatpro;
INSERT INTO hatpro SELECT * FROM mwrt08.hatpro;
'''
