#! /usr/bin/env bash

source /home/chris/local/miniconda3/bin/activate thesis

python run_optest.py full cosmo cosmo &
#python run_optest.py vband cosmo cosmo &
python run_optest.py zenith cosmo cosmo &

python run_optest.py full regression regression &

python run_optest.py full regression cosmo &
python run_optest.py full cosmo regression &

wait
